-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."batch_document_type" AS ENUM('assembly_list', 'picking_list', 'merged_label_slips');--> statement-breakpoint
CREATE TYPE "public"."display_fulfillment_status" AS ENUM('FULFILLED', 'IN_PROGRESS', 'ON_HOLD', 'OPEN', 'PARTIALLY_FULFILLED', 'PENDING_FULFILLMENT', 'RESTOCKED', 'SCHEDULED', 'UNFULFILLED', 'REQUEST_DECLINED');--> statement-breakpoint
CREATE TYPE "public"."fulfillment_priority" AS ENUM('normal', 'urgent', 'critical', 'low');--> statement-breakpoint
CREATE TYPE "public"."garment_size" AS ENUM('xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', 'os');--> statement-breakpoint
CREATE TYPE "public"."garment_type" AS ENUM('coat', 'jacket', 'hoodie', 'crewneck', 'longsleeve', 'tee', 'shorts', 'sweatpants', 'headwear', 'accessory');--> statement-breakpoint
CREATE TYPE "public"."line_item_completion_status" AS ENUM('not_printed', 'partially_printed', 'printed', 'in_stock', 'oos_blank', 'skipped', 'ignore');--> statement-breakpoint
CREATE TYPE "public"."log_type" AS ENUM('INFO', 'WARN', 'ERROR');--> statement-breakpoint
CREATE TYPE "public"."order_hold_cause" AS ENUM('address_issue', 'shipping_issue', 'stock_shortage', 'other');--> statement-breakpoint
CREATE TYPE "public"."order_log_category" AS ENUM('SHIPPING', 'ASSEMBLY');--> statement-breakpoint
CREATE TYPE "public"."print_location" AS ENUM('front', 'back', 'left_sleeve', 'right_sleeve', 'other');--> statement-breakpoint
CREATE TYPE "public"."product_status" AS ENUM('ACTIVE', 'DRAFT', 'ARCHIVED');--> statement-breakpoint
CREATE TYPE "public"."shipment_api" AS ENUM('SHIPPO', 'EASYPOST');--> statement-breakpoint
CREATE TYPE "public"."shipping_priority" AS ENUM('express', 'fastest', 'standard');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('running', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'superadmin', 'staff', 'creator', 'va', 'warehouse');--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completedItems" bigint NOT NULL,
	"totalItems" bigint NOT NULL,
	"status" "task_status" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shipments" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"api" "shipment_api" DEFAULT 'SHIPPO' NOT NULL,
	"shipment_id" text NOT NULL,
	"chosen_rate_id" text,
	"order_id" text NOT NULL,
	"line_item_ids" text[],
	"parcel_snapshot" json NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"shippo_transaction_id" text,
	"label_slip_path" text,
	"plain_slip_path" text,
	"is_purchased" boolean DEFAULT false NOT NULL,
	"is_refunded" boolean DEFAULT false,
	"chosen_carrier_name" text
);
--> statement-breakpoint
ALTER TABLE "shipments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "order_holds" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_holds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"cause" "order_hold_cause" NOT NULL,
	"reason_notes" text NOT NULL,
	"is_resolved" boolean DEFAULT false NOT NULL,
	"order_id" text NOT NULL,
	"order_number" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "batch_documents" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"document_path" text PRIMARY KEY NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"batch_id" integer,
	"document_notes" text DEFAULT '' NOT NULL,
	"document_type" "batch_document_type" NOT NULL,
	"merged_pdf_order_ids" text[],
	CONSTRAINT "batch_documents_document_path_key" UNIQUE("document_path")
);
--> statement-breakpoint
CREATE TABLE "blanks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"blank_company" text NOT NULL,
	"blank_name" text NOT NULL,
	"garment_type" "garment_type" NOT NULL,
	"links" text[] NOT NULL,
	"customs_price" double precision NOT NULL
);
--> statement-breakpoint
ALTER TABLE "blanks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "prints" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location" "print_location" NOT NULL,
	"heat_transfer_code" text,
	"is_small_print" boolean,
	"product_id" text
);
--> statement-breakpoint
CREATE TABLE "print_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"line_item_id" text NOT NULL,
	"print_id" uuid,
	"active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text)
);
--> statement-breakpoint
CREATE TABLE "blank_variants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"size" "garment_size" NOT NULL,
	"color" text NOT NULL,
	"blank_id" uuid NOT NULL,
	"weight" double precision NOT NULL,
	"volume" double precision NOT NULL,
	"quantity" bigint DEFAULT '0' NOT NULL,
	CONSTRAINT "blank_variants_color_size_blank_id_key" UNIQUE("size","color","blank_id")
);
--> statement-breakpoint
CREATE TABLE "logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" "log_type" DEFAULT 'INFO' NOT NULL,
	"category" "order_log_category",
	"message" text NOT NULL,
	"order_id" text
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"username" text NOT NULL,
	"email" text NOT NULL,
	"creator_vendor_name" text,
	"role" "user_role" DEFAULT 'staff' NOT NULL,
	CONSTRAINT "profiles_username_key" UNIQUE("username"),
	CONSTRAINT "profiles_email_key" UNIQUE("email"),
	CONSTRAINT "creator profiles_vendor_name_key" UNIQUE("creator_vendor_name")
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "product_variants" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"title" text NOT NULL,
	"price" text NOT NULL,
	"product_id" text NOT NULL,
	"warehouse_inventory" integer DEFAULT 0 NOT NULL,
	"blank_variant_id" uuid
);
--> statement-breakpoint
ALTER TABLE "product_variants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "products" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"title" text NOT NULL,
	"vendor" text NOT NULL,
	"status" "product_status" DEFAULT 'DRAFT' NOT NULL,
	"blank_id" uuid,
	"is_black_label" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "creator_payout" (
	"creator_name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"amount" double precision NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "batches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_batch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"assembly_line_json" text
);
--> statement-breakpoint
ALTER TABLE "batches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "order_notes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"order_id" text NOT NULL,
	"profile_id" uuid NOT NULL,
	"note" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "line_items" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"name" text NOT NULL,
	"order_id" text NOT NULL,
	"variant_id" text,
	"product_id" text,
	"completion_status" "line_item_completion_status" DEFAULT 'not_printed' NOT NULL,
	"quantity" bigint DEFAULT '1' NOT NULL,
	"has_deprecated_blank_stock" boolean,
	"has_deprecated_variant_stock" boolean,
	"marked_as_packaged" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"name" text NOT NULL,
	"queued" boolean DEFAULT true NOT NULL,
	"fulfillment_priority" "fulfillment_priority" DEFAULT 'normal' NOT NULL,
	"shipping_priority" "shipping_priority" DEFAULT 'standard' NOT NULL,
	"display_fulfillment_status" "display_fulfillment_status" NOT NULL,
	"display_customer_name" text,
	"display_destination_country_name" text,
	"display_destination_country_code" text,
	"display_is_cancelled" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "orders_batches" (
	"order_id" text NOT NULL,
	"batch_id" integer NOT NULL,
	CONSTRAINT "orders_session_batches_pkey" PRIMARY KEY("order_id","batch_id")
);
--> statement-breakpoint
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_holds" ADD CONSTRAINT "order_holds_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "batch_documents" ADD CONSTRAINT "batch_documents_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "public"."batches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prints" ADD CONSTRAINT "print_info_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_line_item_id_fkey" FOREIGN KEY ("line_item_id") REFERENCES "public"."line_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_print_id_fkey" FOREIGN KEY ("print_id") REFERENCES "public"."prints"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blank_variants" ADD CONSTRAINT "blank_variants_blank_id_fkey" FOREIGN KEY ("blank_id") REFERENCES "public"."blanks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "logs" ADD CONSTRAINT "logs_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_variants" ADD CONSTRAINT "gql_product_variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_blank_variant_id_fkey" FOREIGN KEY ("blank_variant_id") REFERENCES "public"."blank_variants"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_blank_id_fkey" FOREIGN KEY ("blank_id") REFERENCES "public"."blanks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creator_payout" ADD CONSTRAINT "creator_payout_creator_name_fkey" FOREIGN KEY ("creator_name") REFERENCES "public"."profiles"("creator_vendor_name") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_notes" ADD CONSTRAINT "order_notes_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_notes" ADD CONSTRAINT "order_notes_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_items" ADD CONSTRAINT "gql_line_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_items" ADD CONSTRAINT "gql_line_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_items" ADD CONSTRAINT "gql_line_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders_batches" ADD CONSTRAINT "orders_batches_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "public"."batches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders_batches" ADD CONSTRAINT "orders_session_batches_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active" ON "batches" USING btree ("active" bool_ops) WHERE active;--> statement-breakpoint
CREATE INDEX "orders_name_idx" ON "orders" USING btree ("name" text_ops);--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "shipments" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "blanks" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "profiles" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "product_variants" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "products" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "batches" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "orders" AS PERMISSIVE FOR ALL TO "authenticated" USING ((auth.uid() IS NOT NULL));
*/